export const HTTP_STATUS = {
	OK: 200,
	CREATED: 201,
	ACCEPTED: 202,
	NO_CONTENT: 204,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	PAYMENT_REQUIRED: 402,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	METHOD_NOT_ALLOWED: 405,
	CONFLICT: 409,
	UNPROCESSABLE_ENTITY: 422,
	TOO_MANY_REQUESTS: 429,
	INTERNAL_SERVER_ERROR: 500,
	BAD_GATEWAY: 502,
	SERVICE_UNAVAILABLE: 503,
	GATEWAY_TIMEOUT: 504,
} as const;

export type HttpStatusCode = (typeof HTTP_STATUS)[keyof typeof HTTP_STATUS];

export const HTTP_STATUS_TEXT: Record<HttpStatusCode, string> = {
	[HTTP_STATUS.OK]: "OK",
	[HTTP_STATUS.CREATED]: "Created",
	[HTTP_STATUS.ACCEPTED]: "Accepted",
	[HTTP_STATUS.NO_CONTENT]: "No Content",
	[HTTP_STATUS.BAD_REQUEST]: "Bad Request",
	[HTTP_STATUS.UNAUTHORIZED]: "Unauthorized",
	[HTTP_STATUS.PAYMENT_REQUIRED]: "Payment Required",
	[HTTP_STATUS.FORBIDDEN]: "Forbidden",
	[HTTP_STATUS.NOT_FOUND]: "Not Found",
	[HTTP_STATUS.METHOD_NOT_ALLOWED]: "Method Not Allowed",
	[HTTP_STATUS.CONFLICT]: "Conflict",
	[HTTP_STATUS.UNPROCESSABLE_ENTITY]: "Unprocessable Entity",
	[HTTP_STATUS.TOO_MANY_REQUESTS]: "Too Many Requests",
	[HTTP_STATUS.INTERNAL_SERVER_ERROR]: "Internal Server Error",
	[HTTP_STATUS.BAD_GATEWAY]: "Bad Gateway",
	[HTTP_STATUS.SERVICE_UNAVAILABLE]: "Service Unavailable",
	[HTTP_STATUS.GATEWAY_TIMEOUT]: "Gateway Timeout",
};

export function isErrorHttpStatus(statusCode: number): boolean {
	return statusCode >= 400;
}
